apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gatekeeper.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "gatekeeper.name" . }}
    {{- include "gatekeeper.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gatekeeper.name" . }}
      {{- include "gatekeeper.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "gatekeeper.name" . }}
        {{- include "gatekeeper.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "gatekeeper.name" . }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
      containers:
        - name: gatekeeper
          image: "{{ .Values.gatekeeper.image }}:{{ .Values.gatekeeper.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
            requests:
              cpu: 100m
              memory: 20Mi
