apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gatekeeper.name" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "gatekeeper.name" . }}-controller
    control-plane: controller-manager
    gatekeeper.sh/operation: webhook
    gatekeeper.sh/system: "yes"
    {{- include "gatekeeper.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gatekeeper.name" . }}-controller
      {{- include "gatekeeper.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "gatekeeper.name" . }}-controller
        {{- include "gatekeeper.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "gatekeeper.name" . }}
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - all
        readOnlyRootFilesystem: true
        runAsGroup: 999
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: gatekeeper
          image: "quay.io/karavel/opa-gatekeeper-crds:v{{ .Values.controller.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
            requests:
              cpu: 100m
              memory: 20Mi
