apiVersion: v1
kind: Service
metadata:
  name: {{ include "gatekeeper.name" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "gatekeeper.name" . }}-controller
    control-plane: controller-manager
    gatekeeper.sh/operation: webhook
    gatekeeper.sh/system: "yes"
    {{- include "gatekeeper.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: webhook-server
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: {{ include "gatekeeper.name" . }}-controller
    control-plane: controller-manager
    gatekeeper.sh/operation: webhook
    gatekeeper.sh/system: "yes"
    {{- include "gatekeeper.selectorLabels" . | nindent 4 }}
