apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "gatekeeper.name" . }}-admin-upgrade-crds
  labels:
    app: '{{ template "gatekeeper.name" . }}'
    chart: '{{ template "gatekeeper.name" . }}'
    gatekeeper.sh/system: "yes"
    heritage: '{{ .Release.Service }}'
    release: '{{ .Release.Name }}'
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: "hook-succeeded,before-hook-creation"
    helm.sh/hook-weight: "1"
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "gatekeeper.name" . }}-admin-upgrade-crds
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: "hook-succeeded,before-hook-creation"
    helm.sh/hook-weight: "1"
subjects:
  - kind: ServiceAccount
    name: {{ include "gatekeeper.name" . }}-admin-upgrade-crds
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "gatekeeper.name" . }}-admin-upgrade-crds
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ include "gatekeeper.name" . }}-admin-upgrade-crds
  namespace: '{{ .Release.Namespace }}'
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: "hook-succeeded,before-hook-creation"
    helm.sh/hook-weight: "1"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "gatekeeper.name" . }}-update-crds-hook
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "gatekeeper.name" . }}
    chart: {{ template "gatekeeper.name" . }}
    gatekeeper.sh/system: "yes"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "1"
    helm.sh/hook-delete-policy: "hook-succeeded,before-hook-creation"
spec:
  backoffLimit: 0
  template:
    metadata:
      name: {{ include "gatekeeper.name" . }}-update-crds-hook
    spec:
      serviceAccountName: {{ include "gatekeeper.name" . }}-admin-upgrade-crds
      restartPolicy: Never
      containers:
      - name: crds-upgrade
        image: "quay.io/karavel/opa-gatekeeper-crds:v{{ .Values.controller.tag | default .Chart.AppVersion }}"
        imagePullPolicy: '{{ .Values.image.pullPolicy }}'
        args:
        - apply
        - -f
        - crds/
        resources:
          {{- toYaml .Values.crds.resources | nindent 10 }}
        securityContext:
          {{- toYaml .Values.crds.securityContext | nindent 10 }}
      affinity:
        {{- toYaml .Values.upgradeCRDs.affinity | nindent 8 }}
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        {{- toYaml .Values.upgradeCRDs.tolerations | nindent 8 }}