{{- if .Values.prometheus.enable }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "gatekeeper.name" . }}-audit
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "gatekeeper.name" . }}-audit
    app.kubernetes.io/component: audit
    {{ include "gatekeeper.labels" . | nindent 4 }}
spec:
  endpoints:
    - path: /metrics
      port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gatekeeper.name" . }}-audit
      app.kubernetes.io/component: audit
      {{ include "gatekeeper.selectorLabels" . | nindent 6 }}
{{- end }}
